package com.fullsecurity.server;

import java.util.ArrayList;

public class Cheeses {
    public final ArrayList<String> cheeses = new ArrayList<>(380);

    public Cheeses() {
        cheeses.add("Abertam cheese");
        cheeses.add("Acre");
        cheeses.add("Adobera cheese");
        cheeses.add("Afuega\'l pitu");
        cheeses.add("Akkawi");
        cheeses.add("Allgäuer Bergkäse");
        cheeses.add("Alto Alentejo");
        cheeses.add("Anari cheese");
        cheeses.add("Andean Aconcagua region");
        cheeses.add("Anthotyros");
        cheeses.add("Appenzell");
        cheeses.add("Appenzeller");
        cheeses.add("Ardrahan Cheese");
        cheeses.add("Areesh");
        cheeses.add("Asadero cheese");
        cheeses.add("Asturias");
        cheeses.add("Atleet");
        cheeses.add("Aura");
        cheeses.add("Ayibe");
        cheeses.add("Azores");
        cheeses.add("Añejo cheese");
        cheeses.add("Babybel");
        cheeses.add("Bandel");
        cheeses.add("Basket cheese");
        cheeses.add("Bałtycki");
        cheeses.add("Beira Baixa");
        cheeses.add("Belgium");
        cheeses.add("Belo Sirenje");
        cheeses.add("Bergenost");
        cheeses.add("Bergkäse");
        cheeses.add("Berner Alpkäse");
        cheeses.add("Beyaz peynir");
        cheeses.add("Bilozhar");
        cheeses.add("Bjurholm, Sweden");
        cheeses.add("Blå Gotland");
        cheeses.add("Bonifaz");
        cheeses.add("Brick cheese");
        cheeses.add("Brunost");
        cheeses.add("Brussels cheese");
        cheeses.add("Bryndza");
        cheeses.add("Bryndza Podhalańska");
        cheeses.add("Brânză de Suhaia");
        cheeses.add("Brânzǎ de burduf");
        cheeses.add("Bukovinskyi");
        cheeses.add("Bundz");
        cheeses.add("Bursztyn");
        cheeses.add("Burträsk");
        cheeses.add("Butterkäse");
        cheeses.add("Byaslag");
        cheeses.add("Cabrales cheese");
        cheeses.add("Cambozola");
        cheeses.add("Cantabria");
        cheeses.add("Caravane cheese");
        cheeses.add("Castelo Branco cheese");
        cheeses.add("Catalonia");
        cheeses.add("Catupiry");
        cheeses.add("Caş");
        cheeses.add("Caşcaval");
        cheeses.add("Chanco cheese");
        cheeses.add("Chaqueño");
        cheeses.add("Chechil");
        cheeses.add("Cheddar Cheese");
        cheeses.add("Cheese curds");
        cheeses.add("Cherni Vit");
        cheeses.add("Chhena");
        cheeses.add("Chhurpi");
        cheeses.add("Chiapas cheese");
        cheeses.add("Chihuahua cheese");
        cheeses.add("Chimay cheeses");
        cheeses.add("Chloro");
        cheeses.add("Chura kampo");
        cheeses.add("Chura loenpa");
        cheeses.add("Circassian cheese");
        cheeses.add("Colby cheese");
        cheeses.add("Colby-Jack cheese");
        cheeses.add("Colorado");
        cheeses.add("Colorado Blackie");
        cheeses.add("Cotija cheese");
        cheeses.add("Cottage cheese");
        cheeses.add("Cougar Gold cheese");
        cheeses.add("County Cork");
        cheeses.add("Cream cheese");
        cheeses.add("Crema");
        cheeses.add("Cremoso cheese");
        cheeses.add("Creole cream cheese");
        cheeses.add("Crete");
        cheeses.add("Criollo");
        cheeses.add("Criollo cheese");
        cheeses.add("Croatian island of Pag");
        cheeses.add("Cuajada");
        cheeses.add("Cup Cheese");
        cheeses.add("Dahi Chhena");
        cheeses.add("Danbo");
        cheeses.add("Danish Blue");
        cheeses.add("Dimsi");
        cheeses.add("Dobrodar");
        cheeses.add("Domiati");
        cheeses.add("Edamski");
        cheeses.add("Eesti Juust");
        cheeses.add("Emmentaler");
        cheeses.add("Esrom");
        cheeses.add("Extremadura");
        cheeses.add("Farmer cheese");
        cheeses.add("Feta");
        cheeses.add("Flower of Rajya");
        cheeses.add("Fuerteventura, Canary Islands");
        cheeses.add("Fynbo");
        cheeses.add("Galicia");
        cheeses.add("Gamalost");
        cheeses.add("Gamonedo cheese");
        cheeses.add("Garrotxa cheese");
        cheeses.add("Gauda");
        cheeses.add("Geitost");
        cheeses.add("Government cheese");
        cheeses.add("Goya");
        cheeses.add("Gołka");
        cheeses.add("Graviera");
        cheeses.add("Grevé");
        cheeses.add("Gruyère");
        cheeses.add("Gryficki");
        cheeses.add("Gräddost");
        cheeses.add("Guayana Region");
        cheeses.add("Guayanés cheese");
        cheeses.add("Gudbrandsdalsost");
        cheeses.add("Halloumi");
        cheeses.add("Handkäse");
        cheeses.add("Harzer");
        cheeses.add("Hauskyjza");
        cheeses.add("Havarti");
        cheeses.add("Hellim");
        cheeses.add("Herrgårdsost");
        cheeses.add("Herve cheese");
        cheeses.add("Hirtenkäse");
        cheeses.add("Hoop cheese");
        cheeses.add("Hushållsost");
        cheeses.add("Höfðingi");
        cheeses.add("Idiazábal cheese");
        cheeses.add("Imsil");
        cheeses.add("Jameed");
        cheeses.add("Jarlsberg cheese");
        cheeses.add("Jibneh Arabieh");
        cheeses.add("Jāņi cheese");
        cheeses.add("Kadaka juust");
        cheeses.add("Kalari");
        cheeses.add("Kalimpong cheese");
        cheeses.add("Karaván");
        cheeses.add("Kashkaval");
        cheeses.add("Kashkawan");
        cheeses.add("Kasseri");
        cheeses.add("Kačkavalj");
        cheeses.add("Kaşar");
        cheeses.add("Kefalograviera");
        cheeses.add("Kefalotyri");
        cheeses.add("Kelle Peyniri (Balıkesir)");
        cheeses.add("Kesong puti");
        cheeses.add("Khoya");
        cheeses.add("Kopanisti");
        cheeses.add("Korall");
        cheeses.add("Korbáčiky");
        cheeses.add("Kortowski");
        cheeses.add("Koryciński");
        cheeses.add("Kravská hrudka");
        cheeses.add("Kunik cheese");
        cheeses.add("L\'Etivaz");
        cheeses.add("La Mancha, Castile–La Mancha");
        cheeses.add("La Serena cheese");
        cheeses.add("Labne");
        cheeses.add("Labneh");
        cheeses.add("Land of Herve, Belgium");
        cheeses.add("Lapland");
        cheeses.add("Lappi");
        cheeses.add("Latvijas");
        cheeses.add("Le Wavreumont");
        cheeses.add("Lechicki");
        cheeses.add("Leipäjuusto");
        cheeses.add("León");
        cheeses.add("Liederkranz cheese");
        cheeses.add("Lighvan cheese");
        cheeses.add("Liliput");
        cheeses.add("Limburger");
        cheeses.add("Limburger cheese");
        cheeses.add("Lingallin");
        cheeses.add("Liptauer");
        cheeses.add("Liptauer or Kőrözött");
        cheeses.add("Liqvan");
        cheeses.add("Livno cheese");
        cheeses.add("Livno, Bosnia and Herzegovina");
        cheeses.add("Liège, Belgium");
        cheeses.add("Lolland");
        cheeses.add("Lubuski");
        cheeses.add("Lüneberg cheese");
        cheeses.add("Majdoule");
        cheeses.add("Majorero cheese");
        cheeses.add("Malaka");
        cheeses.add("Manchego cheese");
        cheeses.add("Manouri");
        cheeses.add("Maredsous cheese");
        cheeses.add("Maribo");
        cheeses.add("Mató cheese");
        cheeses.add("Maytag Blue cheese");
        cheeses.add("Mazurski");
        cheeses.add("Menonita");
        cheeses.add("Metsovone");
        cheeses.add("Mihaliç");
        cheeses.add("Milbenkäse");
        cheeses.add("Minas");
        cheeses.add("Mish");
        cheeses.add("Mohant");
        cheeses.add("Molbo");
        cheeses.add("Mols");
        cheeses.add("Mondseer");
        cheeses.add("Monte Enebro cheese");
        cheeses.add("Monterey Jack cheese");
        cheeses.add("Moose cheese");
        cheeses.add("Motal");
        cheeses.add("Muenster cheese");
        cheeses.add("Murcia");
        cheeses.add("Murcian cheese");
        cheeses.add("Myconos");
        cheeses.add("Myzithra");
        cheeses.add("Nablus");
        cheeses.add("Nabulsi cheese");
        cheeses.add("Nacho cheese");
        cheeses.add("Navarre and Basque Country");
        cheeses.add("Nguri");
        cheeses.add("Norvegia");
        cheeses.add("Nøkkelost");
        cheeses.add("Năsal cheese");
        cheeses.add("Oaxaca cheese");
        cheeses.add("Oka");
        cheeses.add("Olomoucké syrečky");
        cheeses.add("Oltermanni");
        cheeses.add("Orava");
        cheeses.add("Orda");
        cheeses.add("Oscypek");
        cheeses.add("Otlu (Van)");
        cheeses.add("Ovčia hrudka");
        cheeses.add("Oázis");
        cheeses.add("Oštiepok");
        cheeses.add("Paneer");
        cheeses.add("Pannónia");
        cheeses.add("Panquehue");
        cheeses.add("Parenica");
        cheeses.add("Passendale cheese");
        cheeses.add("Passendale, Belgium");
        cheeses.add("Paški sir");
        cheeses.add("Pepper jack cheese");
        cheeses.add("Picón Bejes-Tresviso");
        cheeses.add("Pinconning cheese");
        cheeses.add("Provel cheese");
        cheeses.add("Province of Ávila");
        cheeses.add("Przeworski");
        cheeses.add("Prästost");
        cheeses.add("Pule cheese");
        cheeses.add("Pultost");
        cheeses.add("Pálpusztai");
        cheeses.add("Queijo Canastra");
        cheeses.add("Queijo Cobocó");
        cheeses.add("Queijo Manteiga");
        cheeses.add("Queijo Meia Cura");
        cheeses.add("Queijo coalho");
        cheeses.add("Queijo de Colônia");
        cheeses.add("Queijo de Nisa");
        cheeses.add("Queijo do Pico");
        cheeses.add("Queijo do Serro");
        cheeses.add("Queijo prato");
        cheeses.add("Queijo seco");
        cheeses.add("Queijo-do-Reino");
        cheeses.add("Quesillo");
        cheeses.add("Queso Campesino");
        cheeses.add("Queso Crema");
        cheeses.add("Queso Cuajada");
        cheeses.add("Queso Fresco");
        cheeses.add("Queso Llanero");
        cheeses.add("Queso Paipa");
        cheeses.add("Queso Palmita");
        cheeses.add("Queso Panela");
        cheeses.add("Queso blanco");
        cheeses.add("Queso crineja");
        cheeses.add("Queso de cuajo");
        cheeses.add("Queso de mano");
        cheeses.add("Queso semiduro");
        cheeses.add("Queso telita");
        cheeses.add("Questo Costeño");
        cheeses.add("Raclette");
        cheeses.add("Radamer");
        cheeses.add("Raejuusto");
        cheeses.add("Rauchkäse");
        cheeses.add("Red Hawk");
        cheeses.add("Redykołka");
        cheeses.add("Reggianito");
        cheeses.add("Remoudou");
        cheeses.add("Renaico");
        cheeses.add("Requeijão");
        cheeses.add("Rice cheese");
        cheeses.add("Rodoric");
        cheeses.add("Rokpol");
        cheeses.add("Romadur");
        cheeses.add("Roncal cheese");
        cheeses.add("Roumy cheese");
        cheeses.add("Rubing");
        cheeses.add("Rushan");
        cheeses.add("Saaremaa");
        cheeses.add("Safed");
        cheeses.add("Saga");
        cheeses.add("Sakura cheese");
        cheeses.add("Saloio");
        cheeses.add("Samsø");
        cheeses.add("Samsø cheese");
        cheeses.add("Santarém cheese");
        cheeses.add("Santorini");
        cheeses.add("Sardo");
        cheeses.add("Sbrinz");
        cheeses.add("Schabziger");
        cheeses.add("Serra da Estrela");
        cheeses.add("Shanklish");
        cheeses.add("Sirene");
        cheeses.add("Smetankowyi");
        cheeses.add("Smoked cheese");
        cheeses.add("Snøfrisk");
        cheeses.add("So (dairy product)");
        cheeses.add("Southern Ostrobothnia, Kainuu");
        cheeses.add("Soy cheese");
        cheeses.add("String cheese");
        cheeses.add("Stånga");
        cheeses.add("Sulguni");
        cheeses.add("Surti Paneer");
        cheeses.add("Svecia");
        cheeses.add("Swiss cheese");
        cheeses.add("Syr");
        cheeses.add("Syrian cheese");
        cheeses.add("São Jorge");
        cheeses.add("Słupski chłopczyk");
        cheeses.add("Tandil");
        cheeses.add("Teleme cheese");
        cheeses.add("Telemea");
        cheeses.add("Tetilla cheese");
        cheeses.add("Tilsit cheese");
        cheeses.add("Tilsiter");
        cheeses.add("Tolmin");
        cheeses.add("Tolminc cheese");
        cheeses.add("Torta del Casar");
        cheeses.add("Tounjski");
        cheeses.add("Trappista cheese");
        cheeses.add("Travnik, Bosnia and Herzegovina");
        cheeses.add("Travnički (Vlašić) cheese");
        cheeses.add("Tulum");
        cheeses.add("Tupí");
        cheeses.add("Tvaroh");
        cheeses.add("Tvorog (творог)");
        cheeses.add("Twaróg");
        cheeses.add("Tybo");
        cheeses.add("Tylżycki");
        cheeses.add("Tyrolean grey (Tiroler Graukäse)");
        cheeses.add("Tyrozouli");
        cheeses.add("Tzfat cheese");
        cheeses.add("Tête de Moine");
        cheeses.add("Ukraїnskyi");
        cheeses.add("Urda");
        cheeses.add("Urdă");
        cheeses.add("Urdǎ");
        cheeses.add("Vacherin Fribourgeois");
        cheeses.add("Vacherin Mont d\'Or");
        cheeses.add("Valdeón cheese");
        cheeses.add("Vesterhavsost");
        cheeses.add("Vurda");
        cheeses.add("Västerbottensost");
        cheeses.add("Wagasi");
        cheeses.add("Weisslacker");
        cheeses.add("Wisconsin");
        cheeses.add("Xynomizithra");
        cheeses.add("Xynotyro");
        cheeses.add("Zamojski");
        cheeses.add("Zamora");
        cheeses.add("Zamorano cheese");
        cheeses.add("Zgorzelecki");
        cheeses.add("Ädelost");
        cheeses.add("Ġbejna");
        cheeses.add("Łowicki");
        cheeses.add("Škripavac");
    }
}
