package com.fullsecurity.server;

import android.util.Log;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;

@SuppressWarnings("all")
public class PdfManager {

    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);

    public PdfManager(String fullFileName) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(new File(fullFileName)));
            document.open();
            addMetaData(document);
            addTitlePage(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            Log.d("JIM","Exception"+e.toString());
        }
    }

    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitlePage(Document document)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("Title of the document", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph(
                "This document describes something which is very important ",
                smallBold));

        addEmptyLine(preface, 8);

        preface.add(new Paragraph(
                "This document is a preliminary version and not subject to your license agreement or any other agreement.",
                redFont));

        document.add(preface);
        // Start a new page
        document.newPage();
    }

    private static void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("First Chapter", catFont);
        anchor.setName("First Chapter");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Paragraph 1"));
        subCatPart.add(new Paragraph("Paragraph 2"));
        subCatPart.add(new Paragraph("Paragraph 3"));

        // add a list
        createList(subCatPart);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // add a table
        createTable(subCatPart);

        // now add all this to the document
        document.add(catPart);

        // Next section
        anchor = new Anchor("Second Chapter", catFont);
        anchor.setName("Second Chapter");

        // Second parameter is the number of the chapter
        catPart = new Chapter(new Paragraph(anchor), 1);

        subPara = new Paragraph("Subcategory", subFont);
        subCatPart = catPart.addSection(subPara);
        String s =


                "------------------" +
                        "System Information" +
                        "------------------" +
                        "Time of this report: 5/27/2014, 09:59:24" +
                        "   Operating System: Windows 7 Home Premium 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_gdr.140303-2144)" +
                        "           Language: English (Regional Setting: English)" +
                        "System Manufacturer: TOSHIBA" +
                        "       System Model: Satellite P775" +
                        "               BIOS: BIOS Date: 10/30/12 11:36:36 Ver: AMI APTIO 2.20" +
                        "          Processor: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 CPUs), ~2.5GHz" +
                        "             Memory: 6144MB RAM" +
                        "Available OS Memory: 6052MB RAM" +
                        "          Page File: 5806MB used, 6295MB available" +
                        "        Windows Dir: C:windows" +
                        "    DirectX Version: DirectX 11" +
                        "DX Setup Parameters: Not found" +
                        "   User DPI Setting: Using System DPI" +
                        " System DPI Setting: 96 DPI (100 percent)" +
                        "    DWM DPI Scaling: Disabled" +
                        "     DxDiag Version: 6.01.7601.17514 32bit Unicode" +
                        "" +
                        "------------" +
                        "DxDiag Notes" +
                        "------------" +
                        "        Sound Tab 1: No problems found." +
                        "          Input Tab: No problems found." +
                        "" +
                        "--------------------" +
                        "DirectX Debug Levels" +
                        "--------------------" +
                        "Direct3D:    0/4 (retail)" +
                        "DirectDraw:  0/4 (retail)" +
                        "DirectInput: 0/5 (retail)" +
                        "DirectMusic: 0/5 (retail)" +
                        "DirectPlay:  0/9 (retail)" +
                        "DirectSound: 0/5 (retail)" +
                        "DirectShow:  0/6 (retail)" +
                        "" +
                        "---------------" +
                        "Display Devices" +
                        "---------------" +
                        "-------------" +
                        "Sound Devices" +
                        "-------------" +
                        "            Description: Speakers (Realtek High Definition Audio)" +
                        " Default Sound Playback: Yes" +
                        " Default Voice Playback: Yes" +
                        "            Hardware ID: HDAUDIOFUNC_01&VEN_10EC&DEV_0269&SUBSYS_1179FC08&REV_1001" +
                        "        Manufacturer ID: 1" +
                        "             Product ID: 100" +
                        "                   Type: WDM" +
                        "            Driver Name: RTKVHD64.sys" +
                        "         Driver Version: 6.00.0001.6323 (English)" +
                        "      Driver Attributes: Final Retail" +
                        "            WHQL Logo'd: Yes" +
                        "          Date and Size: 3/8/2011 21:44:54, 2799848 bytes" +
                        "            Other Files: " +
                        "        Driver Provider: Realtek Semiconductor Corp." +
                        "         HW Accel Level: Basic" +
                        "              Cap Flags: 0xF1F" +
                        "    Min/Max Sample Rate: 100, 200000" +
                        "Static/Strm HW Mix Bufs: 1, 0" +
                        " Static/Strm HW 3D Bufs: 0, 0" +
                        "              HW Memory: 0" +
                        "       Voice Management: No" +
                        " EAX(tm) 2.0 Listen/Src: No, No" +
                        "   I3DL2(tm) Listen/Src: No, No" +
                        "Sensaura(tm) ZoomFX(tm): No" +
                        "" +
                        "---------------------" +
                        "Sound Capture Devices" +
                        "---------------------" +
                        "            Description: Microphone (Realtek High Definition Audio)" +
                        "  Default Sound Capture: Yes" +
                        "  Default Voice Capture: Yes" +
                        "            Driver Name: RTKVHD64.sys" +
                        "         Driver Version: 6.00.0001.6323 (English)" +
                        "      Driver Attributes: Final Retail" +
                        "          Date and Size: 3/8/2011 21:44:54, 2799848 bytes" +
                        "              Cap Flags: 0x1" +
                        "           Format Flags: 0xFFFFF" +
                        "" +
                        "-------------------" +
                        "DirectInput Devices" +
                        "-------------------" +
                        "      Device Name: Keyboard" +
                        "         Attached: 1" +
                        "    Controller ID: n/a" +
                        "Vendor/Product ID: n/a" +
                        "        FF Driver: n/a" +
                        "" +
                        "      Device Name: USB Receiver" +
                        "         Attached: 1" +
                        "    Controller ID: 0x0" +
                        "Vendor/Product ID: 0x046D, 0xC52F" +
                        "        FF Driver: n/a" +
                        "" +
                        "      Device Name: USB Receiver" +
                        "         Attached: 1" +
                        "    Controller ID: 0x0" +
                        "Vendor/Product ID: 0x046D, 0xC52F" +
                        "        FF Driver: n/a" +
                        "" +
                        "      Device Name: USB Receiver" +
                        "         Attached: 1" +
                        "    Controller ID: 0x0" +
                        "Vendor/Product ID: 0x046D, 0xC52F" +
                        "        FF Driver: n/a" +
                        "" +
                        "Poll w/ Interrupt: No" +
                        "" +
                        "-----------" +
                        "USB Devices" +
                        "-----------" +
                        "+ USB Root Hub" +
                        "| Vendor/Product ID: 0x8086, 0x1C2D" +
                        "| Matching Device ID: usb\root_hub20" +
                        "| Service: usbhub" +
                        "| " +
                        "+-+ Generic USB Hub" +
                        "| | Vendor/Product ID: 0x8087, 0x0024" +
                        "| | Location: Port_#0001.Hub_#0001" +
                        "| | Matching Device ID: usbclass_09" +
                        "| | Service: usbhub" +
                        "" +
                        "----------------" +
                        "Gameport Devices" +
                        "----------------" +
                        "" +
                        "------------" +
                        "PS/2 Devices" +
                        "------------" +
                        "+ Standard PS/2 Keyboard" +
                        "| Matching Device ID: *pnp0303" +
                        "| Service: i8042prt" +
                        "| " +
                        "+ Terminal Server Keyboard Driver" +
                        "| Matching Device ID: root\rdp_kbd" +
                        "| Upper Filters: kbdclass" +
                        "| Service: TermDD" +
                        "| " +
                        "+ Synaptics PS/2 Port TouchPad" +
                        "| Matching Device ID: *tos0300" +
                        "| Upper Filters: SynTP" +
                        "| Service: i8042prt" +
                        "| " +
                        "+ HID-compliant mouse" +
                        "| Vendor/Product ID: 0x046D, 0xC52F" +
                        "| Matching Device ID: hid_device_system_mouse" +
                        "| Service: mouhid" +
                        "| " +
                        "+ Terminal Server Mouse Driver" +
                        "| Matching Device ID: root\rdp_mou" +
                        "| Upper Filters: mouclass" +
                        "| Service: TermDD" +
                        "" +
                        "------------------------" +
                        "Disk & DVD/CD-ROM Drives" +
                        "------------------------" +
                        "      Drive: C:" +
                        " Free Space: 535.9 GB" +
                        "Total Space: 698.4 GB" +
                        "File System: NTFS" +
                        "      Model: Hitachi HTS547575A9E384" +
                        "" +
                        "      Drive: Q:" +
                        "      Model: n/a" +
                        "" +
                        "      Drive: D:" +
                        "      Model: TSSTcorp CDDVDW SN-208AB" +
                        "     Driver: c:windowssystem32driverscdrom.sys, 6.01.7601.17514 (English), , 0 bytes" +
                        "" +
                        "--------------" +
                        "System Devices" +
                        "--------------" +
                        "     Name: High Definition Audio Controller" +
                        "Device ID: PCIVEN_8086&DEV_1C20&SUBSYS_FC301179&REV_043&11583659&0&D8" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: 2nd generation Intel® Core™ processor family DRAM Controller - 0104" +
                        "Device ID: PCIVEN_8086&DEV_0104&SUBSYS_FC001179&REV_093&11583659&0&00" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 6 - 1C1A" +
                        "Device ID: PCIVEN_8086&DEV_1C1A&SUBSYS_FC301179&REV_B43&11583659&0&E5" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 4 - 1C16" +
                        "Device ID: PCIVEN_8086&DEV_1C16&SUBSYS_FC301179&REV_B43&11583659&0&E3" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: LPC Interface Controller" +
                        "Device ID: PCIVEN_8086&DEV_1C49&SUBSYS_FC301179&REV_043&11583659&0&F8" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 2 - 1C12" +
                        "Device ID: PCIVEN_8086&DEV_1C12&SUBSYS_FC301179&REV_B43&11583659&0&E1" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) Management Engine Interface" +
                        "Device ID: PCIVEN_8086&DEV_1C3A&SUBSYS_FC301179&REV_043&11583659&0&B0" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family PCI Express Root Port 1 - 1C10" +
                        "Device ID: PCIVEN_8086&DEV_1C10&SUBSYS_FC301179&REV_B43&11583659&0&E0" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family USB Enhanced Host Controller - 1C2D" +
                        "Device ID: PCIVEN_8086&DEV_1C2D&SUBSYS_FC301179&REV_043&11583659&0&D0" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) Mobile Express Chipset SATA AHCI Controller" +
                        "Device ID: PCIVEN_8086&DEV_1C03&SUBSYS_FC301179&REV_043&11583659&0&FA" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Realtek PCIe GBE Family Controller" +
                        "Device ID: PCIVEN_10EC&DEV_8168&SUBSYS_FC301179&REV_064&1068A457&0&00E0" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family USB Enhanced Host Controller - 1C26" +
                        "Device ID: PCIVEN_8086&DEV_1C26&SUBSYS_FC301179&REV_043&11583659&0&E8" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) Centrino(R) Wireless-N 6150" +
                        "Device ID: PCIVEN_8086&DEV_0885&SUBSYS_13058086&REV_674&200004B7&0&00E1" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Renesas Electronics USB 3.0 Host Controller" +
                        "Device ID: PCIVEN_1033&DEV_0194&SUBSYS_FC301179&REV_044&31F6DD7F&0&00E5" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) 6 Series/C200 Series Chipset Family SMBus Controller - 1C22" +
                        "Device ID: PCIVEN_8086&DEV_1C22&SUBSYS_FC301179&REV_043&11583659&0&FB" +
                        "   Driver: n/a" +
                        "" +
                        "     Name: Intel(R) HD Graphics Family" +
                        "Device ID: PCIVEN_8086&DEV_0126&SUBSYS_FC001179&REV_093&11583659&0&10" +
                        "   Driver: n/a" +
                        "" +
                        "------------------" +
                        "DirectShow Filters" +
                        "------------------" +
                        "" +
                        "DirectShow Filters:" +
                        "WMAudio Decoder DMO,0x00800800,1,1,WMADMOD.DLL,6.01.7601.17514" +
                        "WMAPro over S/PDIF DMO,0x00600800,1,1,WMADMOD.DLL,6.01.7601.17514" +
                        "WMSpeech Decoder DMO,0x00600800,1,1,WMSPDMOD.DLL,6.01.7601.17514" +
                        "MP3 Decoder DMO,0x00600800,1,1,mp3dmod.dll,6.01.7600.16385" +
                        "G2M Session Decoder,0x00600000,1,1,G2M.dll,6.03.0000.1415" +
                        "Mpeg4s Decoder DMO,0x00800001,1,1,mp4sdecd.dll,6.01.7600.16385" +
                        "WMV Screen decoder DMO,0x00600800,1,1,wmvsdecd.dll,6.01.7601.17514" +
                        "WMVideo Decoder DMO,0x00800001,1,1,wmvdecod.dll,6.01.7601.18221" +
                        "Mpeg43 Decoder DMO,0x00800001,1,1,mp43decd.dll,6.01.7600.16385" +
                        "Mpeg4 Decoder DMO,0x00800001,1,1,mpg4decd.dll,6.01.7600.16385" +
                        "WD Secure Source Filter,0x00200000,0,1,WDSecureSourceFilter.dll,2.01.0042.0000" +
                        "WMT VIH2 Fix,0x00200000,1,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "Record Queue,0x00200000,1,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "WMT Switch Filter,0x00200000,1,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "WMT Virtual Renderer,0x00200000,1,0,WLXVAFilt.dll,15.04.3538.0513" +
                        "WMT DV Extract,0x00200000,1,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "WMT Virtual Source,0x00200000,0,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "WMT Sample Information Filter,0x00200000,1,1,WLXVAFilt.dll,15.04.3538.0513" +
                        "TOSHIBA AAC Decoder,0x00600000,1,1,TosRawAACDecoder.ax,3.00.0000.0005" +
                        "DV Muxer,0x00400000,0,0,qdv.dll,6.06.7601.17514" +
                        "Color Space Converter,0x00400001,1,1,quartz.dll,6.06.7601.17713" +
                        "LogMeIn Video Encoder,0x00200000,1,1,," +
                        "WM ASF Reader,0x00400000,0,0,qasf.dll,12.00.7601.17514" +
                        "Screen Capture filter,0x00200000,0,1,wmpsrcwp.dll,12.00.7601.17514" +
                        "AVI Splitter,0x00600000,1,1,quartz.dll,6.06.7601.17713" +
                        "VGA 16 Color Ditherer,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "SBE2MediaTypeProfile,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "Microsoft DTV-DVD Video Decoder,0x005fffff,2,4,msmpeg2vdec.dll,12.00.9200.16426" +
                        "DS Video Buffer Filter,0x00200000,1,1,DSBuffer_Video.ax,2.01.0042.0000" +
                        "AC3 Parser Filter,0x00600000,1,1,mpg2splt.ax,6.06.7601.17528" +
                        "TOSHIBA MP4 Navigator,0x00200000,0,1,MP4NaviFilter.ax," +
                        "StreamBufferSink,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "MJPEG Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.17713" +
                        "MPEG-I Stream Splitter,0x00600000,1,2,quartz.dll,6.06.7601.17713" +
                        "SAMI (CC) Parser,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "MainConcept AAC Encoder,0x00100000,1,1,mc_enc_aac_ds.ax,8.00.0000.43595" +
                        "VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.17514" +
                        "MPEG-2 Splitter,0x005fffff,1,0,mpg2splt.ax,6.06.7601.17528" +
                        "Closed Captions Analysis Filter,0x00200000,2,5,cca.dll,6.06.7601.17514" +
                        "SBE2FileScan,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "Microsoft MPEG-2 Video Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.17514" +
                        "LogMeIn Video Decoder,0x00800000,1,1,," +
                        "Internal Script Command Renderer,0x00800001,1,0,quartz.dll,6.06.7601.17713" +
                        "MPEG Audio Decoder,0x03680001,1,1,quartz.dll,6.06.7601.17713" +
                        "PlayReady DMO Wrapper,0x00600002,1,1,PRDMOW~1.DLL,1.03.2297.0000" +
                        "DV Splitter,0x00600000,1,2,qdv.dll,6.06.7601.17514" +
                        "Video Mixing Renderer 9,0x00200000,1,0,quartz.dll,6.06.7601.17713" +
                        "MS PR Source Filter,0x00200000,0,2,PRSource.dll,1.03.2297.0000" +
                        "TOSHIBA Audio Rate Converter,0x00200000,1,1,TosARC.ax,2.00.0001.0004" +
                        "AC3 Decoder Filter,0x00200000,1,1,," +
                        "Microsoft MPEG-2 Encoder,0x00200000,2,1,msmpeg2enc.dll,6.01.7601.17514" +
                        "TOSHIBA Audio Back Switcher,0x00200000,2,1,TosAudioBackSwitcher.ax," +
                        "TOSHIBA DVD Navigator,0x00200000,0,3,tdvdnavi.ax,1.00.0000.0071" +
                        "Xvid MPEG-4 Video Decoder,0x00800000,1,1,," +
                        "ACM Wrapper,0x00600000,1,1,quartz.dll,6.06.7601.17713" +
                        "Video Renderer,0x00800001,1,0,quartz.dll,6.06.7601.17713" +
                        "MPEG-2 Video Stream Analyzer,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "Line 21 Decoder,0x00600000,1,1,qdvd.dll,6.06.7601.17713" +
                        "Video Port Manager,0x00600000,2,1,quartz.dll,6.06.7601.17713" +
                        "Video Renderer,0x00400000,1,0,quartz.dll,6.06.7601.17713" +
                        "TOSHIBA Progress Monitor,0x00200000,1,1,TProgMon.ax,1.00.0001.0209" +
                        "TOSHIBA WAV Converter,0x00200000,0,0,TWavConv.ax,1.00.0000.0315" +
                        "File Writer,0x00200000,1,0,WLXVAFilt.dll,15.04.3538.0513" +
                        "VPS Decoder,0x00200000,0,0,WSTPager.ax,6.06.7601.17514" +
                        "TOSHIBA DVD VR Navigator,0x00200000,0,3,tvrnavi.ax,1.00.0000.0001" +
                        "WM ASF Writer,0x00400000,0,0,qasf.dll,12.00.7601.17514" +
                        "VBI Surface Allocator,0x00600000,1,1,vbisurf.ax,6.01.7601.17514" +
                        "File writer,0x00200000,1,0,qcap.dll,6.06.7601.17514" +
                        "iTV Data Sink,0x00600000,1,0,itvdata.dll,6.06.7601.17514" +
                        "iTV Data Capture filter,0x00600000,1,1,itvdata.dll,6.06.7601.17514" +
                        "PGTimeStamp,0x00200000,1,1,PGTimeFilter.dll,2.00.0000.0010" +
                        "TOSHIBA Audio Front Switcher,0x00200000,1,2,TosAudioFrontSwitcher.ax," +
                        "Intel® Mux Renderer,0x00200000,2,0,IntelMux.dll,2.01.0042.0000" +
                        "DVD Navigator,0x00200000,0,3,qdvd.dll,6.06.7601.17713" +
                        "Overlay Mixer2,0x00200000,1,1,qdvd.dll,6.06.7601.17713" +
                        "AVI Draw,0x00600064,9,1,quartz.dll,6.06.7601.17713" +
                        "RDP DShow Redirection Filter,0xffffffff,1,0,DShowRdpFilter.dll," +
                        "Microsoft MPEG-2 Audio Encoder,0x00200000,1,1,msmpeg2enc.dll,6.01.7601.17514" +
                        "WST Pager,0x00200000,1,1,WSTPager.ax,6.06.7601.17514" +
                        "MPEG-2 Demultiplexer,0x00600000,1,1,mpg2splt.ax,6.06.7601.17528" +
                        "DV Video Decoder,0x00800000,1,1,qdv.dll,6.06.7601.17514" +
                        "TOSHIBA DualMono,0x00200000,1,1,TosDualMono.ax,2.00.0001.0000" +
                        "SampleGrabber,0x00200000,1,1,qedit.dll,6.06.7601.18386" +
                        "Null Renderer,0x00200000,1,0,qedit.dll,6.06.7601.18386" +
                        "MPEG-2 Sections and Tables,0x005fffff,1,0,Mpeg2Data.ax,6.06.7601.17514" +
                        "Microsoft AC3 Encoder,0x00200000,1,1,msac3enc.dll,6.01.7601.17514" +
                        "StreamBufferSource,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "Smart Tee,0x00200000,1,2,qcap.dll,6.06.7601.17514" +
                        "Overlay Mixer,0x00200000,0,0,qdvd.dll,6.06.7601.17713" +
                        "AVI Decompressor,0x00600000,1,1,quartz.dll,6.06.7601.17713" +
                        "WD Audio Filter,0x00200000,0,1,WDAudioFilter.dll,2.01.0042.0000" +
                        "AVI/WAV File Source,0x00400000,0,2,quartz.dll,6.06.7601.17713" +
                        "Wave Parser,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "MIDI Parser,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "Multi-file Parser,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "File stream renderer,0x00400000,1,1,quartz.dll,6.06.7601.17713" +
                        "TOSHIBA Audio Decoder DVD,0x00200000,1,1,TosAudDecL.ax,2.00.0001.0007" +
                        "Microsoft DTV-DVD Audio Decoder,0x005fffff,1,1,msmpeg2adec.dll,6.01.7140.0000" +
                        "StreamBufferSink2,0x00200000,0,0,sbe.dll,6.06.7601.17528" +
                        "AVI Mux,0x00200000,1,0,qcap.dll,6.06.7601.17514" +
                        "Line 21 Decoder 2,0x00600002,1,1,quartz.dll,6.06.7601.17713" +
                        "File Source (Async.),0x00400000,0,1,quartz.dll,6.06.7601.17713" +
                        "File Source (URL),0x00400000,0,1,quartz.dll,6.06.7601.17713" +
                        "WDSource Filter,0x00200000,0,1,WDSourceFilter.dll,2.01.0042.0000" +
                        "Infinite Pin Tee Filter,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "Enhanced Video Renderer,0x00200000,1,0,evr.dll,6.01.7601.17514" +
                        "Intel®WiDi H264 encoder,0x00200000,1,1,h264_enc_filter.dll," +
                        "BDA MPEG2 Transport Information Filter,0x00200000,2,0,psisrndr.ax,6.06.7601.17669" +
                        "MyFree Codec Filter,0x00200000,0,0,," +
                        "MPEG Video Decoder,0x40000001,1,1,quartz.dll,6.06.7601.17713" +
                        "" +
                        "WDM Streaming Tee/Splitter Devices:" +
                        "Tee/Sink-to-Sink Converter,0x00200000,1,1,ksproxy.ax,6.01.7601.17514" +
                        "" +
                        "Video Compressors:" +
                        "Ligos MPEG-2 Encoder (Intel) v1.9-MT,0x00000000,1,1,LigosDMOVid.dll,2.01.0042.0000" +
                        "WMVideo8 Encoder DMO,0x00600800,1,1,wmvxencd.dll,6.01.7600.16385" +
                        "WMVideo9 Encoder DMO,0x00600800,1,1,wmvencod.dll,6.01.7600.16385" +
                        "MSScreen 9 encoder DMO,0x00600800,1,1,wmvsencd.dll,6.01.7600.16385" +
                        "DV Video Encoder,0x00200000,0,0,qdv.dll,6.06.7601.17514" +
                        "LogMeIn Video Encoder,0x00200000,1,1,," +
                        "MJPEG Compressor,0x00200000,0,0,quartz.dll,6.06.7601.17713" +
                        "Cinepak Codec by Radius,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "Intel IYUV codec,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "Intel IYUV codec,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "Microsoft RLE,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "Microsoft Video 1,0x00200000,1,1,qcap.dll,6.06.7601.17514" +
                        "" +
                        "Audio Compressors:" +
                        "WM Speech Encoder DMO,0x00600800,1,1,WMSPDMOE.DLL,6.01.7600.16385" +
                        "WMAudio Encoder DMO,0x00600800,1,1,WMADMOE.DLL,6.01.7600.16385" +
                        "MainConcept AAC Encoder,0x00100000,1,1,mc_enc_aac_ds.ax,8.00.0000.43595" +
                        "IMA ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "PCM,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "Microsoft ADPCM,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "GSM 6.10,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "Messenger Audio Codec,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "CCITT A-Law,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "CCITT u-Law,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "MPEG Layer-3,0x00200000,1,1,quartz.dll,6.06.7601.17713" +
                        "" +
                        "Audio Capture Sources:" +
                        "Microphone (Realtek High Defini,0x00200000,0,0,qcap.dll,6.06.7601.17514" +
                        "" +
                        "PBDA CP Filters:" +
                        "PBDA DTFilter,0x00600000,1,1,CPFilters.dll,6.06.7601.17528" +
                        "PBDA ETFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.17528" +
                        "PBDA PTFilter,0x00200000,0,0,CPFilters.dll,6.06.7601.17528" +
                        "" +
                        "Midi Renderers:" +
                        "Default MidiOut Device,0x00800000,1,0,quartz.dll,6.06.7601.17713" +
                        "Microsoft GS Wavetable Synth,0x00200000,1,0,quartz.dll,6.06.7601.17713" +
                        "" +
                        "WDM Streaming Capture Devices:" +
                        "Realtek HD Audio Mic input,0x00200000,1,1,ksproxy.ax,6.01.7601.17514" +
                        "Realtek HD Audio Stereo input,0x00200000,1,1,ksproxy.ax,6.01.7601.17514" +
                        "USB 2.0 Camera,0x00200000,1,2,ksproxy.ax,6.01.7601.17514" +
                        "" +
                        "WDM Streaming Rendering Devices:" +
                        "Realtek HD Audio output,0x00200000,1,1,ksproxy.ax,6.01.7601.17514" +
                        "" +
                        "BDA Network Providers:" +
                        "Microsoft ATSC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514" +
                        "Microsoft DVBC Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514" +
                        "Microsoft DVBS Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514" +
                        "Microsoft DVBT Network Provider,0x00200000,0,1,MSDvbNP.ax,6.06.7601.17514" +
                        "Microsoft Network Provider,0x00200000,0,1,MSNP.ax,6.06.7601.17514" +
                        "" +
                        "Video Capture Sources:" +
                        "USB 2.0 Camera,0x00200000,1,2,ksproxy.ax,6.01.7601.17514" +
                        "" +
                        "Multi-Instance Capable VBI Codecs:" +
                        "VBI Codec,0x00600000,1,4,VBICodec.ax,6.06.7601.17514" +
                        "" +
                        "BDA Transport Information Renderers:" +
                        "BDA MPEG2 Transport Information Filter,0x00600000,2,0,psisrndr.ax,6.06.7601.17669" +
                        "MPEG-2 Sections and Tables,0x00600000,1,0,Mpeg2Data.ax,6.06.7601.17514" +
                        "" +
                        "BDA CP/CA Filters:" +
                        "Decrypt/Tag,0x00600000,1,1,EncDec.dll,6.06.7601.17708" +
                        "Encrypt/Tag,0x00200000,0,0,EncDec.dll,6.06.7601.17708" +
                        "PTFilter,0x00200000,0,0,EncDec.dll,6.06.7601.17708" +
                        "XDS Codec,0x00200000,0,0,EncDec.dll,6.06.7601.17708" +
                        "" +
                        "WDM Streaming Communication Transforms:" +
                        "Tee/Sink-to-Sink Converter,0x00200000,1,1,ksproxy.ax,6.01.7601.17514" +
                        "" +
                        "Audio Renderers:" +
                        "Speakers (Realtek High Definiti,0x00200000,1,0,quartz.dll,6.06.7601.17713" +
                        "Default DirectSound Device,0x00800000,1,0,quartz.dll,6.06.7601.17713" +
                        "Default WaveOut Device,0x00200000,1,0,quartz.dll,6.06.7601.17713" +
                        "DirectSound: Speakers (Realtek High Definition Audio),0x00200000,1,0,quartz.dll,6.06.7601.17713" +
                        "" +
                        "---------------" +
                        "EVR Power Information" +
                        "---------------" +
                        "Current Setting: {5C67A112-A4C9-483F-B4A7-1D473BECAFDC} (Quality) " +
                        "  Quality Flags: 2576" +
                        "    Enabled:" +
                        "    Force throttling" +
                        "    Allow half deinterlace" +
                        "    Allow scaling" +
                        "    Decode Power Usage: 100" +
                        "  Balanced Flags: 1424" +
                        "    Enabled:" +
                        "    Force throttling" +
                        "    Allow batching" +
                        "    Force half deinterlace" +
                        "    Force scaling" +
                        "    Decode Power Usage: 50" +
                        "  PowerFlags: 1424" +
                        "    Enabled:" +
                        "    Force throttling" +
                        "    Allow batching" +
                        "    Force half deinterlace" +
                        "    Force scaling" +
                        "    Decode Power Usage: 0";        
                
                
                
        for (int k = 0; k < 200; k++) subCatPart.add(new Paragraph(s));

        // now add all this to the document
        document.add(catPart);

    }

    private static void createTable(Section subCatPart)
            throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 2"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 3"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);

    }

    private static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}